server:
  port: 8765
spring:
  banner:
    location: /banner.txt
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

ssh:
  username: ubuntu
  password: 111111
  port: 22
  host: localhost